"""fix missing user_profile field

Revision ID: f51e2140da0c
Revises: 643ce622d07f
Create Date: 2023-07-27 16:19:27.073104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51e2140da0c'
down_revision = '643ce622d07f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
