name: test app

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'

    # run linter
    - name: Install dependencies
      run: |
        pip install flake8

    - name: Lint with flake8
      run: |
        flake8 app

    # build docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: prepare to build image
      run: |
        cp .env_example .env
        cp ./app/.env_example.test ./app/.env

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # run test
    - name: Run test
      run: |
        docker compose run api sh -c "cd app && pytest"